---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - adguard-home
  #- cloudflare-ddns # no needed already on fw
  - external-dns
  - ingress-nginx
  - metallb
  - k8s-gateway
  - cert-manager
  - uptime-kuma
  - wg-access-server
