# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:xiywTTBLKh6kufJVIq/cvR2KhlzDGgDoAg==,iv:vw0/vO0KWQKknJfgxi9dRFLCLo+wUKBCUb+Ql7mkPBs=,tag:rykQrXyZNUcIpMsDxHfBuA==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:LqUvsYY0eAlBMOZyvIZ4Xb2ydGQs+WXBH0SKjBVu+9EGM3VBYA==,iv:6d+nfzDZbvgVpaxy/d9AoK4bzPIjXDk8+ExL232+6rM=,tag:xJyV2ijNJK6fZIKWnT9eFA==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:HxbDchku7rXIt5epSUc=,iv:SuOfntGWLmim4x9HMkUEe+12HX0/PMz/dx7egfzc7T0=,tag:K7PaF9kZEIyTk8Uhr4EAfA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age158a78lg5z2eu5jqu3xc2z8q3am9pa2gk3t2zv4u7qy00lw7gffqs8xujed
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBycXBuSEJ4d3QyejNCZm1u
            eDBYUEg0MHk1dGJnRWtYU0hFVjBUZTdGdWxRCmROK1hlaTVWRHc5N3AxamNEOS9o
            ZzIxcmV0RjFhamJXc2trenBBTmJrOWcKLS0tIE1FNFpXL3hma3Z5QTdFQ1Zya0NS
            enYxU1g2ZFlmT2Jab0RWTnZSVXVjRDAKj1jCHqHjEoen3JLOHRrwSfWWQ/WoacXe
            T75Bwr8uB0eOExyKvPBi/1EfzBssX+BQAtN8+p1wbMH3x5TGeoPHsA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-14T17:59:21Z"
    mac: ENC[AES256_GCM,data:7CIE3S18sr9Z9zo4baeH8K0Ia7tTvT+WjEwHjKJ872Z7odvaWlf3dZhvJ76m3Y3id8f/yaxNPUUvStShLeOYwL9adLixgMpBwiQNDXaMOmH32CGxFiGqHFbTT0VLmXdCS3ZzWJo4CIv/fWL/3NKIt0UrT18RE/rjCOVNfYt+K6U=,iv:c208HbEUrXZi/iSpFDipCF1Usi19q211OCRiGYZfX8s=,tag:AuZm4jKu6V2SBCpQl88t1w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
