# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:9DXW1aKiFclrV5jetjKldPHKZL3dpmszHg==,iv:q/CmxeuvTQFlRp9KZ28zFW9QOlOEwQZOlOe4Iqg2SoA=,tag:08IdJHaXkuzJB7btLx0WjA==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:0TEaS1WNgPw9LlBEb5rqpgGvVbxNCN65MIUCNx6vc1WeovBbzg==,iv:bovFWDaFQFS6e2ljoKFHsvmiG18YsRDV3x79Rc8f/MU=,tag:hpyb7KYlsxxJEOLRWYk2Sw==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:q54UH9LqZxW8XsfHo3w=,iv:/YQCC/2LvhrQB8wIvVdYxjgM4VwxtHYF9vfvZsknTDY=,tag:gyfVUeLzkvjH2hjRnx4Ckg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age158a78lg5z2eu5jqu3xc2z8q3am9pa2gk3t2zv4u7qy00lw7gffqs8xujed
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtSmtvN0xBL0xlZHhGWUpl
            aFZPUUJicEV3eEpRL2laSGFwYnd0aThqelZjCjJqdWtXUlBQaTFGNVdCRG1nclVr
            SVdBeldZODYzTXZDTW5rczc0N0ZiK1UKLS0tIE16N1YvUzRLR2RHTjI2ejVNSjNK
            dkIvaWFDTUNJbm5nWTB2RTR1Zm9lcTgK+1oFw45yKduH03+PnbyhUouOVfh0GcLQ
            fWJCELoZTuLvjV7UyaLD10wHcA3hO+LDVtZjB4+6ouJJerISk4fN5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-16T17:31:54Z"
    mac: ENC[AES256_GCM,data:4QgzByo2tP5wEdyemeThKstsig9IH/b17kHsb+XTtJFUi4tqcjAXarQRb2E90ETaaYkRDzpqaUUMGz26jf1+KSu3WCVF5sbth3UxDrpBMc4N0bFbZEV9nOjJ2fJ+b0HtbL3XpPJTZ7T8iOQkndE8uVe5hA9Xeh0bPZu3X5seCjw=,iv:j3SwY0FTxPlVb8YZBqGh+TGPAsCoS/SAfF1+dey+/kQ=,tag:r9LHnue28C0gsYMGxE/iUg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
