---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-config
  namespace: networking
spec:
  accessModes:
    - ReadWriteOnce
  #storageClassName: local-path
  resources:
    requests:
      storage: 200Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-data
  namespace: networking
spec:
  accessModes:
    - ReadWriteOnce
  #storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
