---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: uptime-kuma
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://dirsigler.github.io/uptime-kuma-helm
      chart: uptime-kuma
      version: 0.1.7
      sourceRef:
        kind: HelmRepository
        name: duyet
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5

  values:
    env:
      - TZ: ${CONFIG_TIMEZONE}
    ingress:
      enabled: true
      ingressClassName: "nginx"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
        external-dns/is-public: "true"
        hajimari.io/enable: "true"
        hajimari.io/icon: "weather-sunset"
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        #nginx.ingress.kubernetes.io/auth-signin: "https://oauth2.${SECRET_DOMAIN}/oauth2/start?rd=https://$host"
        #nginx.ingress.kubernetes.io/auth-url: "http://oauth2-proxy.networking.svc.cluster.local/oauth2/auth"
      hosts:
        - host: "uptime-kuma.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - "uptime-kuma.${SECRET_DOMAIN}"
          secretName: "uptime-kuma"
    persistence:
      enabled: true
      existingClaim: uptime-kuma-data
    podAnnotations:
      backup.velero.io/backup-volumes: data
