---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openebs
  namespace: openebs
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://openebs.github.io/charts
      chart: openebs
      version: 3.3.1
      sourceRef:
        kind: HelmRepository
        name: openebs
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    ndm:
      enabled: false
    ndmOperator:
      enabled: false
    cstor:
      enabled: false
      # for k0s
      csiNode:
        kubeletDir: "/var/lib/k0s/kubelet"
