# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:efJkRGzfNMnYwP/KgUVwmojgrS7WoQnZIg==,iv:w4U3irEoJSOPPTh9iC/EZyMxy+3piWdbn7PhC95F/9c=,tag:v0cGfh1cTTa12283qmslZg==,type:str]
    api-key: ENC[AES256_GCM,data:16djO7KgduIUypHvQWRr+3oD3jIdrywV7TmxAUph6mBVNBjaqQ==,iv:GkgPIBymbPKLU6yP0OyjWVWIXJcg8QzD0IXynrWOc9c=,tag:iC/SNlrRnMZ1qYGcdo84tA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age158a78lg5z2eu5jqu3xc2z8q3am9pa2gk3t2zv4u7qy00lw7gffqs8xujed
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5cVBvS3ZkTFVQam9PY0VL
            ckRmb0l3d3prR1Y4OTZNYXZSVFFGby82SG1jCmpaZlkwdnZFNEQrVm5VUlhSbTIy
            RW1GTndKS2NDUDl2WTl2ZDZHNFdtNWsKLS0tIFlqaUlNWnlqa0lGU1hobzJHNjFI
            YW5FMXJhYXBMeFNpcTJ3UWZ6QzcxVHMKwAurbhms2wZR0dI7qsFgu1PyJComlN+F
            KieoZAMa8nl0o3fT8rRFF9cZKy9SV0SIUn2g+OspCpEK2VdHZUjgbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-16T16:51:45Z"
    mac: ENC[AES256_GCM,data:IBqjNETOEZRMA9dTBIf+dRlaUHyD3tpGTkSRZKUO5UZmxr74DqKNqT9U6hjFEPj/8Ikty/zOFKoRR2w3S5bFBxt2fhhXbz1EKuRCNMkJCskvMh3sI859Xn5Xd+Cf/smdAM67YIFKHpToaGR+RDJlKv74MQhygsqMXmbP/W2+pSU=,iv:5o8TjkeqvmZ2fovGwcjYRyRvDmDD9zcZvtt++d9aLrg=,tag:2PYRjiWyOoA8BzZvIgL5TA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
