# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:3/9t0PHaY4Qjy683Ev/eCqRiMO+b7C9BPQ==,iv:7IVWJqgsjOFsbPEP8mshHg8ha9DQUHtpDy/JINjqhsI=,tag:mT1uUS57CuExv2nPPRx98A==,type:str]
    api-key: ENC[AES256_GCM,data:dTxeLkGvjbWYBb/PKJSvx6/BCil02jaEYug9tiS0IRgK9NTDJQ==,iv:zJxoSy0n2JxnE5i61tGgUtYoGfyukXPDcFIrWtdh2OI=,tag:1QjqPASiTISB7oxCi/K3cg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age158a78lg5z2eu5jqu3xc2z8q3am9pa2gk3t2zv4u7qy00lw7gffqs8xujed
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3akxmYVNFN3VCNTVYQi9l
            eTdQRWswY1h6MHdoK0dYODE3dEUwanN5Sm1zCjRYd2hKT0tWWmJQVUJWbmdMYU5F
            MEtWOGNjU0VIU0hXR1RSTDIyNUdrL3MKLS0tIExuaklQYnBFNFBwc0d2a1BWWXBu
            VnFWeXlhR05aQmplTlNCbkx1a0dVV1UKPIYOigA8aS+MMNxL9T/Ak89zsxjT9UtH
            pQu7lwDQhc4giWbAWT6JqyXgRG/1Qy5WOoIOvrvF81gh18TO5v9vPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-20T23:08:04Z"
    mac: ENC[AES256_GCM,data:/HM5l4Q9bedifIR3ZLlkbAd1gYTUi/2j0B0363ApHQLUsWy2ZvNUoazUpuqNvqLgxK5qvUS346oULV8r60S2/l6JgT1vaPbhQ8lvmXOgZUb1X33ew+JH5K247jpMWxH5wiupbx86WrGp+c9rJuoJ5twyhNItklr3ftCTFE0Pfmg=,iv:uc4WbPneAvJdMUdU27HDtiZerve9hDaUrEXPuQmAXOU=,tag:Be/95V94yBuKxBk0HaIZoA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
