# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:WbVT14os38BDeOH3706yat63LsfFZTHWWg==,iv:dkrQ6nh9WzmJRWTDoUiG120BFpQVU2/MtBIzuzDkwlI=,tag:2Pd9GRM8Pf/+c70iV7hSDg==,type:str]
    api-key: ENC[AES256_GCM,data:/nBOzYlkX5KgjUQMgZY6dHEftnTg8O9aGXz8PCfgcxkY3OYIYw==,iv:h4i2fpnt1qSr2GdsfpQD/9/tkeJJqKWagHamkcT8VrA=,tag:VOsy2++T2PWW21Ju+UnhnA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age158a78lg5z2eu5jqu3xc2z8q3am9pa2gk3t2zv4u7qy00lw7gffqs8xujed
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxYzNFZFZObXhJQnd4Ymw2
            ekdFVFFGR1MyZlVpUG5CY09QZ3JZR3g3bTFFCmdCdVBseWIwZFlRSjhoNE9BUjVZ
            YjR4WnJkOWtIUXlmMkpLcmRtcXRTekUKLS0tIEJaYnNLZzNkaEtoWTcxeU5xTUU3
            OGN5SFphMjNkdTNKY0JKYTNxeUM3SHMK1DEabZL2zN5XUflSHijfF6r9niolRc5c
            EGag8auwJWQaPTPQHdmPBu1t6SmOZURJUASrVxcwxqiB9/cqZQrJHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-14T17:59:21Z"
    mac: ENC[AES256_GCM,data:dPCrjKZQ/zHuTux1dluhC6Fk9Zz6yS0E/1rnEtpAQ2w+gN24YhZVfT13/UQG1xFVFR+sCyr5x+q1iga6anvgjjV45V7xfwR70V8QoIPP2l2/Eewqc/Y41t6NtloVH4bGrtdNeWuDofKVRmIjvGrjJiIzsM1OEA1lrtgHXBESFw0=,iv:ALft0JoT5xFTbyjJIT3nJSMtCR+7O+QafPk+7U+Fi78=,tag:2dzkAV1PLZCRzIvpJqv+Sw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
