# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: networking
stringData:
    api-key: ENC[AES256_GCM,data:gwhRMY4yvWROnk80gSJ8hggpUkJFJCw0/iBmQladwc+mLEUQZQ==,iv:iD79bDAQ8z2xPOZlojvJ++xhe0YrlOiNInjIuRCo/P8=,tag:HCz+JlndVFx7vNLpn6ta5w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cksp0nn9tmqq8vvyd978cgxeny4uhgznd4y8yw0knxsf5wxgkgzqsfsx3d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3WUVUN0NyZjRPUzBTYXhL
            cE1mME5wQmdZOUlHN1M5MXY5cUFseXZxVzBjCmZvd09mRVdLeGtHTXlMUFZFYkVF
            eEwrMXRVL0tBbUhacDBYank0WGl2SHcKLS0tIDRsWVIwRFdTREFONUF0ZnA1UmV3
            OE5jWUZSUGtSVHpteWdjM3h5MWkvRkEKZ4K/+zHFtUzuamyMGCXVa2RHs2nV+ec8
            OnDGhgePfcbgSoZ4R+5FoXb3ZtYSBrCIRa0J6/0BUYIbF0ZjrAT8Kw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-14T17:56:30Z"
    mac: ENC[AES256_GCM,data:ImcKkNmghZNCDDnsMGQ8XcEF91990N5UkxrRDlgukwDEeEOurPl+Vf6AJLYXJSJQ2JOK76SUEq/diQawOFY4K5qaUVKyDSZK0YUoccyMkIOvBw9YomJpMIpbkOPedN1u69HoCo+Eh2EdomCFfdsJmwwOZrA2PI0DSqOBnyPEI6Y=,iv:RbzH3Lr5wfmwEkVH13T4tqpT1pCPutR4AtLie3Tql1c=,tag:eBn4N+StucZf5QJIbJD1ng==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
