# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: networking
stringData:
    api-key: ENC[AES256_GCM,data:t9DDhrrBkABFckx98EbC7eomdPUVfWb9VGBvTvHL7ctGOFw4zQ==,iv:q+eWTELGaHwr9FaoQpbiT6tsG9q5Tqm98lVNf/+tSlw=,tag:lysRtb3wQ6V+Cy2ulLdLlw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age158a78lg5z2eu5jqu3xc2z8q3am9pa2gk3t2zv4u7qy00lw7gffqs8xujed
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBldXo1ckpHM3J2amJzRjVk
            MW9WaXhQdG5nUzM1RDdsaXdiMk5JbllDb1U0Cmx6TkNFNkY0NWs0cDFVUHJyc29G
            aktuNWM0OU1JQ2s1Nm1NRmxLVDlQR28KLS0tIEdvRXlWL2phQnlCUXNuVDR1SkxT
            dTRnOGs1K1I4aWM4ODM1UElndWdXT1UKVQEuBO9ITFABKWMJADv/BnQFM+8h9ifb
            TlYzynsdlbis+2m5deUH3pdtX/QDpUqL+pm0AOq7zx/cjxGkukhflg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-20T23:08:04Z"
    mac: ENC[AES256_GCM,data:xmRQOkB9JkZZ2wIftOzuPShVPmxpK5gKhOzCxC3xQ84UdjjFW3J6xjRtRmJMnf/ddnpOwS1p0HsohBBkE9vaa/fbUJ13OYtosaOX1Tm91VICajhl8tlb3Zd4ui0qTQ6/LCHYz5XIP4rGO/GvXaArGWSNfESWy41fdtH/Ww4jnr8=,iv:45TL86iq+QCyWBDBAoSku7kapImrbIAqFv0WawHlmmM=,tag:QkbE+rh30mDYXLpxzYzH8w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
