# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: networking
stringData:
    api-key: ENC[AES256_GCM,data:aOv0WaqC82JxmEAvNGcWpT6OSukIx/5CATb57iCNgZlH1lOtHQ==,iv:Lf+lea5n/zGXViSSIWiE6/gYYrlKN144Dadtk+vu9aU=,tag:JdOsTcirhikkkDDkWVYaBA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age158a78lg5z2eu5jqu3xc2z8q3am9pa2gk3t2zv4u7qy00lw7gffqs8xujed
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsTm5WaFBvK3ZtSGRFck9q
            RDZ3RlVsTmN4dnhzZE1rMlVQa3o4b2ZLRldjCndTaVlvdFQzbTJzQUM0Z2dFQ2FR
            amhYVjZtalpTNjB4VWF2QWVsa0kxejQKLS0tIHBIU2RuQTBhZDIxU3FVSG1wamI5
            TVhsKzA4bUo0bmZ0TmxDYkp5TEZMNFkKnpgSHUTQrOTig8QCwSCaGPdAG0B7hy8U
            /P7bGeWbFLOmXU5woIcQoM7Ky++S6v/jsrwPut9omA58yEIUC8E8rA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-16T17:02:21Z"
    mac: ENC[AES256_GCM,data:E9M/ApWS0o6pXXCtbGcUW5vRDvgG9HNklaANP5gumRSeZ3YqYCckubw/QWWrfp42re2hLDeaR8c6yGnmeCBQfhO5og/1jNrjcoXM8N144WeoRkrsb72qAmXgLWYDL9Hgs/cdFnE7IkmWD5JsOcsDZO2cmybNBQtq4egxhplasq4=,iv:o643rOIBrnkkGZ4uxUWsjdqO5Jt5kJ574uhTCBnmg8g=,tag:BBr3HkeJ/xanX/A/tVhF6A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
