# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:liDU8bH8HM8=,iv:HOC/zUZJOIoSrIUHqCv5Jp6QtT8lu/4plrUGOuT/ZXs=,tag:JXVbzkVunSSwdxPzu9dPVw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:VlAUxzs3QOtMdoEnRrP26T7HLlv2783RtQ==,iv:bIDb0jR16eZ/yYE6UTLH9AXWgZTGTvr3BECQ3pIJaR0=,tag:uQIAqPn8Z19RF8mKj3hLzg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cksp0nn9tmqq8vvyd978cgxeny4uhgznd4y8yw0knxsf5wxgkgzqsfsx3d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjcm5ieTR0d1ZtRWR0Ujd0
            SVo0MDBkdHVWYklmSHd1YWNnNFlFMjdnT1VBCkpDTTgvb3RuMzdkWG5uZGQ1S3N1
            Sk9pTVF1V0ZWa3FDMGxZN0xDeFhTaGsKLS0tIDdLL1dHblljd1JUYWh2bWJ5Tmsy
            cUNIeWZTVHBXNlJ4OFh5VEZ4QXFkV00KM5WGcDFMxAT3MddKxirrm/X7Xv1hgU9d
            jbKws0GvkimUvT0zyBGR1gQ0XS4pyaC2q5BaOpsKYHoxwqy5vmnfYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-04T21:38:25Z"
    mac: ENC[AES256_GCM,data:geOrc5WQpcoWPsD/sP4Qc1WvDEilp6nP/iUVfHLjwBiY0vmoDN4H0yXKVOCiEyv7nRdf3ln1dVqEckMYUu+tTDhRklbOxpRqXsp+cRNWmLK81M+mmacY4igUamJfV01tjD9sOCpYOBXV80Vb672VvSb9Fqx0sZh3YXUtOZcIeTs=,iv:/qdTTZS+y/suDfzMXfSOeSs2mcYyd8RzQZBPl1hWO30=,tag:F251zELXRi41PgZxI+5Rpw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
