# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:5sr+jVKqeajV,iv:yOQWZ5xTu0K8Ubcw2MjJYtCtawCPW7FdWGGlHjuDMEk=,tag:YtbDk3xNVfhszSBdMkSx9A==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:/R883EBUPCsHB0Cc2xYnH2rP+BzewOAqzw==,iv:ZBV6ZePlrrobmXZQt2U4nWDP3QipQIsyeuEDPmSfnqg=,tag:jGSy9JQEAEiTRKLvYrpCHQ==,type:str]
    SECRET_MINIO_ADMIN_KEY: ENC[AES256_GCM,data:JFhJFLHQD/ai,iv:yf1Agoeh4q/hAaxbu7g7V/2s36pg5/d5O/6Ya4wdqp8=,tag:k0GOnUvu11uzwF6+3XJeng==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age158a78lg5z2eu5jqu3xc2z8q3am9pa2gk3t2zv4u7qy00lw7gffqs8xujed
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyRkk4Tml5eEhSTE1FOUVW
            aXlHR2FJR1RWVWRIUmQxSXhlb0VOcFovMEgwClVmbmxpbE95SVcvWnVKdmVjdk9T
            dG9heHdwekpLNVJaN05HY2lBQ1l1akEKLS0tIE5wMTk5TjBNYVlvUWtNSThVbXFw
            dTBLa1JRUE5ZdTcrWkU1R2FSKzUwc2MKi36YTASuVpY8z/htjLeEFOOZf7pBRMAV
            M0Z+JxowwnRi1a1KZiSv/jz7kWViNB43+p++2wk/2QqmXukCYGuBIw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-16T17:02:21Z"
    mac: ENC[AES256_GCM,data:WKvfSr0bWqxv9Gpqs+Id1RJ79O7qv5GhgkXPmA7v6hRPN2bhFvnRJjegYfKha5Jjfz2YL1TN6Mv4rTb3sWrYHHlSQ7d4V7DvR4fwzY9DZVFetEWt5ozMqsDhZuNtBmo54ryAijflEvIfL0PCFq0hbWMBNCV2vl8nz/nzzgHrLiM=,iv:n9pM/3NXlIZClpamXP6zEoKNMV2a1/RnQO38ncQf8O4=,tag:Ip2ZKQYJV3JmYKXTXAToxw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
