# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:Y0zdjG3zqG57,iv:acPWpU4982sH51DVxcK+3d8XAffiDN5jE08+hQZF/V4=,tag:r799CdScuVMtNckU7NulcA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:w2rzu3A/vMcDVhpMa8KGFZnQk1kgJ6McaA==,iv:LgzLK+pNt/wvnTUzj4JDGAOpm1571xYScHU/PsSxXhU=,tag:hrk8x5PUN3xdW6zxpFDhQg==,type:str]
    SECRET_MINIO_ADMIN_KEY: ENC[AES256_GCM,data:23Z2GX/3UXD+,iv:m2TosbPTTbJcPHm/kvAEtAU/e/pstjnRQ1cCa9NObYw=,tag:bamP2nwssG9t8r8lLBt1tQ==,type:str]
    SECRET_OPENHAB_BASICAUTH: ENC[AES256_GCM,data:WhApzNKJ/U/wrOh/J9RTcSyAse5lPIYjdNgEawhU5zynQv/pfdvXjsLkSa8Ni7mtmG4F2oaW2GeJ7PtM,iv:RBlpYg/CUiqpqtT+FHAo/GJedeCYo5zXmuvJN3a9c94=,tag:K74xzfnj39d1Av/YtLcffQ==,type:str]
    SECRET_WG_PRIV_KEY: ENC[AES256_GCM,data:MaLDXk/QvVCCH1A9OcD3kNYqxrOHcz4wxMRHhNXASg/YLYRaFGyW2afnitk=,iv:PKxq3YDSgQYIep8qHNAPS+isILdRnr41p6yR8UO09R8=,tag:bpl/G/z/GnIgFnO5jITELQ==,type:str]
    SECRET_WG_ADMIN_USER: ENC[AES256_GCM,data:HSnP7dU=,iv:jKmR0NpEco++aCk6uuj85mSEkOkUNMwRs2zj25LHxg4=,tag:HUzdYgzheQpyE6sZS34aow==,type:str]
    SECRET_WG_ADMIN_PASSWORD: ENC[AES256_GCM,data:QafdzR+aj/8=,iv:wEGhnIos7P9SNNbGkLXT6JMIpyZTbZmfPibzfKLY9ow=,tag:8BidvAo8RwY9UvoGxBJ0hQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age158a78lg5z2eu5jqu3xc2z8q3am9pa2gk3t2zv4u7qy00lw7gffqs8xujed
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqNDNBbGxRR2hIMjJEVmRh
            NUhqRnNhZm1oQ3Eyb3pZSnNUUHlSN2JSZ1Y4CnFIL3dmdldpTTE2WmVEQTVycUtX
            NFM1aVQxeDdydUdzUDNKMkx0RHhXRzQKLS0tIHh0TmxqSHRTQm5Cb0lONEwvRW9E
            MHQ3NzhLWGM3ZmRLejBMT2JiNGlDZm8Klv8u2WouaL6XMWImvhBnO6+YW9Dv7vEz
            13nG17IkGVuVTmng2hML3VxO1cS8kZq8nygw827o8DF3RX7ZFAAaEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-17T16:32:41Z"
    mac: ENC[AES256_GCM,data:9u43YSpS3JesZD9FcIWtddBV/nZ9w/WQJoT0aH2Kyu/iF64VS1yfHOskcyhLXId/ov+9yhaqFE7wqq0hi53xPot+OsCyGyU8EQ6uJ6E8PqswXMELOE3ekVt1Bk72+X7yrFpLK3h1aS0TY9QbeRqfoIk59RWJMnyrwqmMVA5rlHU=,iv:YjnzEXCok8KFdcE7lzqQl1cVDOPZbbJj+/2jOZdeqQM=,tag:8PHW7E5sMfT28WbKLJ54Ew==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
