# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:73K8IAL5ZmAh,iv:0ksHgivcXgApgZ4ugGk7+KWTLoOKSpOxtk6K/6TCTxA=,tag:ktve2M0Zb42FUkPtttHHeg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:s4EzhCryvCfpws9qIKQTs/y+bGHoO8Fj+g==,iv:/jlTcU3tRoVGoFN9vPYW1/bACD68bGtEVyjMJexexjc=,tag:2+Ix2cgkPDkgLmv75ht39g==,type:str]
    SECRET_MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:DRFpAec+1H4=,iv:ub/LR2AoQ5GmJnkdAx+ZU2/9lAObHjzkr4v6TSCJGrg=,tag:tBhalMlm2VpV5vDCgBT5nA==,type:str]
    SECRET_MINIO_ADMIN_KEY: ENC[AES256_GCM,data:L5Vmt4p1BXAq,iv:Oh1fInoMhCMc3IylitMyY7VaQ/DGwo6JcdxNa0CuTZM=,tag:ZPly/KMmTcvwYkNnu4sDJw==,type:str]
    SECRET_OPENHAB_BASICAUTH: ENC[AES256_GCM,data:TwaDuHRZIZNrcLjqFFq6sIH8+LIPsN32H9vv/OQKfKHpB1ex4tDAFHQRvSi7s+alYMceMSweNdTJ8/mv,iv:ZpFycPk1sWT498Xa+60fQ8TJsdI4Ep2DLXFNiP3IvJ4=,tag:Za5sD66NbvI/iZ8dCj+54A==,type:str]
    SECRET_WG_PRIV_KEY: ENC[AES256_GCM,data:656/pZMdIKsKjYEh9WIUXBa9E6EV/mBOS16LB0ITRsz5/hokKk5Htlsg7E8=,iv:mVv686l96E6fUqJoixrGMLAFdCM1/CzEz9zmb/Nnw9M=,tag:ohXqIx1Cu/v8wF7+VvAmVg==,type:str]
    SECRET_WG_ADMIN_USER: ENC[AES256_GCM,data:owJDMJo=,iv:ZgoIP8X4xxIUvu3Mr07g5xGqRw6z6nhcszS56sGFTWQ=,tag:oUK2/q3UG7MGvRRIiWHt8g==,type:str]
    SECRET_WG_ADMIN_PASSWORD: ENC[AES256_GCM,data:/RrSbY3o7mE=,iv:uAH6p+WWzZuwrakAhRkemGzIGqbVgO0o/IfX8i5eiRQ=,tag:hLM2FC6zm86289W80QQx8w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age158a78lg5z2eu5jqu3xc2z8q3am9pa2gk3t2zv4u7qy00lw7gffqs8xujed
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2Y1lDUVBNdjMrYzNNSXVa
            bERDb0pZR3d5U1lOanU1QS9GK21yMFcrWERzClBkVVk0SU9uU3RFMkhITnhpZG1x
            aU9ZcWhZZVN4T2hoTVVvWVFCMDAzYUkKLS0tIEFwSzI3dk9BV0Q4QnRKZlNqVlJq
            VUJSdmdEMGUzZlIzMTVoTC9OSTFxOVUKNqxrmCi9r2n00OetlTiZi4PeSjncn/aw
            WpdD/jw0MqgpcRCWKeqAIJwm0gkCy6CIw0bzCxLKlIqIl3DBprcKqQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-19T20:20:54Z"
    mac: ENC[AES256_GCM,data:paoFUlfRlexO50wC86WpGBOOtCGkbWqRP0coc7ciy1HMeN496KIDX4aJ3N20HQNyKvWSuBVLefYpeLi3cmNO1DGUHQUVc0ETsSsvsMD1KsvNJ8byDWWfp12vpSh4GHc7Mrh8GPv42XrTi5P0P0hKjC8WjoH1uBC5vldKTVIw4/I=,iv:Gh1gN9XJ7i9H0Mx+edrA173MCcGeyxLZDZb7UkyqcL4=,tag:e+KPDk3juRpiGUPIUYPJ9g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
