---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mongodb
  namespace: db
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: mongodb
      version: 13.5.0
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      tag: 4.4.15-debian-10-r8
    auth:
      usernames:
        - username: admin
      passwords:
        - password: ${SECRET_MONGODB_ROOT_PASSWORD}
      databases:
        - database: default

      rootPassword: ${SECRET_MONGODB_ROOT_PASSWORD}
      username: admin
      password: ${SECRET_MONGODB_ROOT_PASSWORD}

    persistence:
      enabled: true
      existingClaim: mongodb-data
      # podSecurityContext:
      #   enabled: true
      #   fsGroup: 1000
      #containerSecurityContext:
      #  runAsNonRoot: false
      #   enabled: true
      #   runAsUser: 1000
    podAnnotations:
      backup.velero.io/backup-volumes: data
    # resources:
    #   requests:
    #     cpu: 100m
    #     memory: 128Mi
    #   limits:
    #     memory: 256Mi
