---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-data
  namespace: db
spec:
  accessModes:
    - ReadWriteOnce
  #storageClassName: openebs-hostpath
  resources:
    requests:
      storage: 1Gi
