kind: Secret
ansible_user: ENC[AES256_GCM,data:nqp3ur0I,iv:II0Qy1YvkIVEhLhm+dDxQpHaINw7SV4u1tAtspEboCY=,tag:+PoEpIszrSXe8Iz/qVouXQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:6L2YTJb0m1ZYzg==,iv:OQSCQAFtfLYeKO4l7g27vJ6B4jQApg1sNUynSceLK8c=,tag:+IFLbquLPXOTlJIjceygrA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cksp0nn9tmqq8vvyd978cgxeny4uhgznd4y8yw0knxsf5wxgkgzqsfsx3d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuemlzeU8zSlpTUmx3a3BJ
            dzg2eUQ3QTU4SGFXaEgzQjlkNGk2TkxiRnpvCnZhSENkNUdXWlVJZXR0TXZLS2x0
            SWdOK0hXM0Z5dEtrQVYwbUJaOWRyMm8KLS0tIG1ZeTBvZ2paeEx6RUpTV25iN0Jn
            VVZsQ0xHMmdoNGo1UHFuVHVaR21pU3cKzs5nIFk2WHKeuvmfRTgm9p9WX95X8fRE
            jQGzrWFWSmhsCLK9i/ztC2/Dz9hj2ek4p1G4jfQMU7DDPLlcY2ZY3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-09T11:33:04Z"
    mac: ENC[AES256_GCM,data:/CbpNvu3WqFaaIVXHToLJ9RVXF1Q1J/qhGM+cQZo5SdXt+Kv0/qJvz2vgw3rlGPydHLTsMqom06Jb94nVepoxEAY1MjdE1OAQNRCg4e5M+zh/G9FpPirTyseIfZ6Jd80+88pNvV4kG+B6n/hdMzxjRnmOsXB/gMmUVG6faPuq7c=,iv:VeRYzDZnKF5FNNz6oroU7KcPvyd2gkjr7nIqxkN292Q=,tag:lWMDC29RnGHuH6iEex0uDA==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
