kind: Secret
ansible_user: ENC[AES256_GCM,data:OdY+WmAN,iv:cAvUeXva5xvnwx6foM7cuDxpubIgbf3UfTL1ElWJ2P4=,tag:AjERDz1s9GJt38c+ptg4Hg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:0z4JyUTf3YE=,iv:7J3Tk6+eHXXTG92iTEIaBzjjizVMC9jqqCpzR6eUNQw=,tag:Y03r42mgwMmBUP75ugypGw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age158a78lg5z2eu5jqu3xc2z8q3am9pa2gk3t2zv4u7qy00lw7gffqs8xujed
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrdFdtUmJIOTFFalo1T3Np
            dzNOdzJtV1lObE9Jd2JWOStjUk1GVlpidnhNCkwxQ055QmxsdE5zbVBtampPZ1JU
            YnpvaFdFV0w2RkhPcDFoMXJDWEF3Q0EKLS0tIExCNk1FRnNscXB5aWU0eStGcDdL
            VjBoZmdpYVp1L2hMTTFHdFBMUmM4dkEKpDypTMY9aWuVWrfY/Vd/HsfFGxX4amYl
            Nuu6+iMAUJXbKixnA2COJxcMnHav8QiIPReeJChcOxAmyeXl2DG3uA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-20T23:08:04Z"
    mac: ENC[AES256_GCM,data:HftZGL08SzV+l77HdihZoTYI2cX6yVqYtgdZG2dQdUYYUa0nk6F54hR8OWO/tSpXqRPDe2ezv8R9Je8DH27z6fav0NbB3KoI256vOmp2UgAhEXYiStQARB4E1PVDy1dOG6Q4elb3b7uEePIYIvTnzhh0xAhtQ8oVcy4agVX4/Z8=,iv:/KpDLVyTssF22xuJKlizt30ijSCtM5nJv4AWASsuoRo=,tag:dDLiZk6igR0lV5gJW7IMfg==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
