kind: Secret
ansible_user: ENC[AES256_GCM,data:29WzSvnk,iv:jBy+zF7/v1EaRw9rsHtH81s0K01gCvzuzQUgXL9YEfE=,tag:Z12CpWVO4SaLGnwe3E/UXg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:Z0EvxKxMxaw=,iv:otqOUg/5LFqzFl2zkrcluTOeQ4QMLgX7ZndP6+q4HR0=,tag:Sc+4RfbohsAetpDizhfh8g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age158a78lg5z2eu5jqu3xc2z8q3am9pa2gk3t2zv4u7qy00lw7gffqs8xujed
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxRzJjUlNIN3ZZclZKbWVL
            anRKMlFVb3d3RmgxTVdaVkJXNENNZUJnM0hzClJuRXlOM2t5aFJjVFlzSDVPaStP
            QUpPZU05UmowdTk4NnBadUFMVURPN2cKLS0tIFlVbjMvK2FUSmhNYmhBVXpJWExp
            V0ZUcm14SGRiUFdhVFJsdjc5TWRYaTAKVzWLM49ezoQ3L8NRlMJLbRC1doXu+K02
            TGqRmXywAWun3b3BE9l39lGZn2WiclsoXYFdW+ioC0/BZtf3B1v+qA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-16T17:31:54Z"
    mac: ENC[AES256_GCM,data:Va05vphBBpyCsvi/FH+N/nUu48ef9o2B7GXZXTIQdDced8CSOyK3jOa/Mre4FzJmOPagIHh/jmvHRc0um4ZUpE/xQdPNVZXu+ql9j53ZcLp8J6bE7Uh2LMMKqJ47e8Wr/qzzABdBIofxHTRkovfvqhiM4WZLt9jIgYx92y5/O9M=,iv:8oAeANNn9aTpDvH5Aud/i9Do/Kibavr87m5fzLcSSiY=,tag:eo0OOD0xzCKjyLBaUEMcog==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
