kind: Secret
ansible_user: ENC[AES256_GCM,data:PtG6lZzl,iv:5Lt3GXzQM+7CN5RlGtZ7WK9fRnoWr5e2Nr3XkS2Mf00=,tag:yNNxLc1b//pLPdW8yv7yBg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:vD08+HtfJ/8=,iv:BJo3v58tXUDlX4+bOvvDMtp53ofIEW2z8DQIY9qaMZs=,tag:0OuaevaXLocl42INrYta5A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cksp0nn9tmqq8vvyd978cgxeny4uhgznd4y8yw0knxsf5wxgkgzqsfsx3d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSMDhGbTJXeUNydkVqcFRW
            ZVFWODN4SU5WT1JmNWVzTVU0aUJjQjgzUTJZCjdFdk55aC9Ca1Z3bFZTWXU4aldK
            NkhLZXNyUEM2Wm5rNGlrTmQ5ZnM2ZTAKLS0tIElidC82cHBzMFdFT0lTTG5iSHdD
            Q0x5UlcwUjhuVTJVeDd6Q1JFYWZ1eUUK3tExYsf2cI3Vo62NRUvIm6lLCk5uhlx7
            eN13aLRj1cDB1fCw03J8xoLRIyJH9TFzzHi23uJ499xNu56cOnMaxw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-14T17:56:30Z"
    mac: ENC[AES256_GCM,data:kUDRGXK7Y0BDYTuO+Pb4HLmMUp5TcNVkbNrH7bPfFM6JElwNeZPuUW/6NDqVBXKqNzfkhhw/H+CP0vWzsAKMJSgUEXcXjuOA3jfiJW2NT7fpkM5g4doOiYKJPrcFsN5I/JGOo2FUKgv5RcLcTKsKOHVrm/ohqQsPzGelANX2QMc=,iv:aQ3XeL3ZFiO0sLWK8GqdmABMB0uO5CZrTnYBaPIPAg0=,tag:k6IuhhNfimynOy54Gu6VuA==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
