kind: Secret
ansible_user: ENC[AES256_GCM,data:oxx+jB9S,iv:lCCzjhEljE373Io1dK2jN5eEmIQcAN8f24z/S/DLFBU=,tag:XvFre+kXdDqngUBmwhwEaA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:CKTRjgYCElE=,iv:AZlP/M9dF89N6QJ9POS+x6WrJJvZw4l4Tqe5O3Wx2xU=,tag:5RIkUP3/4wQ0WWvhr9tMbA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age158a78lg5z2eu5jqu3xc2z8q3am9pa2gk3t2zv4u7qy00lw7gffqs8xujed
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEMmVXZm05R09VNjNZNDBa
            L1dRTlNxdlZtcUJhZ1liVnhXSUl3U1VoNW5RClVrQWFEazZzMk01aCtrd0tkdU5r
            ZDY3a1dUSURPYUlFT3lLZlNQRWJSUjAKLS0tIEhFUHNlSm5IM0o4bEI2OUVzRUxj
            aktXT1hNZmQvOWRNbUxvZmFYaVp4Z1kKtNfHYfNVh/SfZJ+S/431geYQmZSbNFRb
            rwvCPeUwrGHqdGbmean0igqZdihZs0TSJ1V3h1oEAljsIfkBUrFbvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-16T17:02:21Z"
    mac: ENC[AES256_GCM,data:t2nANTZm8B8q+WZKA4GKWUc54pwCohE+uFD6seqoZEUY+JMipxidw+CD68piF/MK6KSnPCc+ODROFZ48tXVOC6v84YVMoOywHmH3ARCx0d2Oj/OF64g2ulkfm7NGYU2g4wyslWiXH4+Lpejjh568T8U8JYNrzKiVtxlOmPEwa3U=,iv:Wc5sBwo33VhS2jRK1oGPUqiio1/9DFZSlaRsww8NDmY=,tag:ax2o0qLbbSUHN1BBf6kT3g==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
