---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mariadb
  namespace: db
spec:
  interval: 15m
  chart:
    spec:
      chart: mariadb
      version: 11.4.0
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    persistence:
      data:
        enabled: true
        existingClaim: mariadb-data
    podAnnotations:
      backup.velero.io/backup-volumes: data
    # resources:
    #   requests:
    #     cpu: 100m
    #     memory: 128Mi
    #   limits:
    #     memory: 256Mi
