---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-data
  namespace: db
spec:
  accessModes:
    - ReadWriteOnce
  #storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
