# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  SECRET_DOMAIN: ${BOOTSTRAP_CLOUDFLARE_DOMAIN}
  SECRET_CLOUDFLARE_EMAIL: ${BOOTSTRAP_CLOUDFLARE_EMAIL}
  SECRET_MARIADB_ROOT_PASSWORD: ${BOOTSTRAP_MARIADB_ROOT_PASSWORD}
  SECRET_MINIO_ADMIN_KEY: ${BOOTSTRAP_MINIO_ADMIN_KEY}
  SECRET_OPENHAB_BASICAUTH: ${BOOTSTRAP_OPENHAB_BASICAUTH}
  SECRET_WG_PRIV_KEY: ${BOOTSTRAP_WG_PRIV_KEY}
  SECRET_WG_ADMIN_USER: ${BOOTSTRAP_WG_ADMIN_USER}
  SECRET_WG_ADMIN_PASSWORD: ${BOOTSTRAP_WG_ADMIN_PASSWORD}
