---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: ${BOOTSTRAP_TIMEZONE}
  METALLB_LB_RANGE: ${BOOTSTRAP_METALLB_LB_RANGE}
  METALLB_K8S_GATEWAY_ADDR: ${BOOTSTRAP_METALLB_K8S_GATEWAY_ADDR}
  METALLB_INGRESS_ADDR: ${BOOTSTRAP_METALLB_INGRESS_ADDR}
  NFS_SERVER_ADDRESS: ${BOOTSTRAP_NFS_SERVER_ADDRESS}
  NFS_KUBEDATA_PATH: ${BOOTSTRAP_NFS_KUBEDATA_PATH}
  NFS_KUBEPVCS_PATH: ${BOOTSTRAP_NFS_KUBEPVCS_PATH}
