---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - db
  - default
  - flux-system
  - kube-system
  - monitoring
  - networking
  - openebs
  # - system-upgrade
  - velero
