---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wg-access-server
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: wg-access-server
      version: v0.4.6
      sourceRef:
        kind: HelmRepository
        name: wg-access-server
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    # wg-access-server config
    web:
      config:
        adminUsername: ${SECRET_WG_ADMIN_USER}
        adminPassword: ${SECRET_WG_ADMIN_PASSWORD}
      service:
        type: LoadBalancer
        loadBalancerIP: ${LB_IP_WG_EASY}
        annotations:
          metallb.universe.tf/allow-shared-ip: wg
    wireguard:
      config:
        privateKey: ${SECRET_WG_PRIV_KEY}
      service:
        type: LoadBalancer
        loadBalancerIP: ${LB_IP_WG_EASY}
        annotations:
          metallb.universe.tf/allow-shared-ip: wg
    persistence:
      enabled: true
      existingClaim: wg-access-server-config
    # chart BUG (not compatible with new kubernetes versions)
    # ingress:
    #   namespace: "networking"
    #   enabled: true
    #   annotations:
    #     kubernetes.io/ingress.class: "nginx"
    #     cert-manager.io/cluster-issuer: "letsencrypt-production"
    #   hosts:
    #     - vpn.${SECRET_DOMAIN}"
    #   tls:
    #     - hosts:
    #         - vpn.${SECRET_DOMAIN}"
    #       secretName: wg-access-server-tls
    annotations:
      backup.velero.io/backup-volumes: wg-access-server-config
