apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wg-access-server-web
  namespace: networking
  labels:
    app.kubernetes.io/instance: wg-access-server
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: wg-access-server
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    external-dns.alpha.kubernetes.io/target: ipv4${SECRET_DOMAIN}
spec:
  tls:
    - hosts:
        - vpn.${SECRET_DOMAIN}
      secretName: wg-access-server-tls
  rules:
    - host: vpn.${SECRET_DOMAIN}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wg-access-server-web
                port:
                  number: 80
