# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:w4gvwxn7YNzNO7W+GaXfawKJqaDL+x9cjC/v56Dv5YbCECRUKJ2hAg==,iv:ZGxozBH36zhB9GNpisE3tQIqZOobVfpMsgQjhc/HK4U=,tag:u8tB/qvK5PG1Fh/2d8abOQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cksp0nn9tmqq8vvyd978cgxeny4uhgznd4y8yw0knxsf5wxgkgzqsfsx3d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFak5DS3pFckZyQVJuSjNI
            SmtpWmVUdm5VWERMOTRjMHR3d1VNR25mZlJzCnlyNXdoNG5OSWEzZ3ZCdHhlSVhq
            ZytKZHB4azR6Zlh5TXZJVVBBOWtSdWMKLS0tIGdLWTZxQ214UHJlRHZUZUN5QlIy
            bDlqYm9OZy82WXl2emFGaHZJSnp6ckkKZHWJcQsFdNRPPd2Zi4WxAVnb+AcdvwvH
            H30G7Os4ZziijWiXXaKH7L6F30PbdDm4af1tAtTsEI7irH1vXCehWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-09T11:33:04Z"
    mac: ENC[AES256_GCM,data:9BB4iyNG7EWvtljquob1EnEQF021bN6aNVGQzGd1OdanzOepWrbQM3RLglr412s/Benis1UYJVGZ/a79o1MTZLHAhLH67RmZG4sXm05VO+EDUMOP3WyKbduZEPVqHS5h59oRiuLHtHmGmuBZ5Ul19QQpouujsTjICN9VbEGWEw4=,iv:KCgqL3VvmJIqMIbQfN6p+BSH1LVVSQCtPpylXmEdgQM=,tag:E7uwxvPVQEXHS6NQ7JR8IQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
