# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:liEU8fgG48XqWYYnfn5ktGRNPluR1Uo/54Ty7g7Yvz56bgsYIM7tWQ==,iv:ltWHic9fTzIDKXjmXZLIyxyhkF4FqgCEKWPt5cJ0Mio=,tag:tuK7l4zo33vZUKhG2xEDCA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age158a78lg5z2eu5jqu3xc2z8q3am9pa2gk3t2zv4u7qy00lw7gffqs8xujed
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOd0xSSm1TdW8vTFR0c0FL
            MjJCUDdpZEtOUS9WU3VQZ1VsOCsyS2JTelNVClFFcE9LdmVWREwrT2lsT01nN05V
            aXd1QUdMZVc2NGdTTXgxUGlGSFo5Y0EKLS0tIGZZVldieDczQUI0dXRzU3ZiOVBn
            UWxaT2JyV3dnS0F1aVZMWVdQc3lyVGcKtFmgNnWLBa+iCwo3vnTllMDIVkbVbAOD
            Qm//e2moe2113M+s2i8J3vIGrYXpyOYzKPxxTzEvI78Gjxsmo/YPaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-14T17:59:21Z"
    mac: ENC[AES256_GCM,data:rTHOEjnY7osW6rpq8oOYR3z3GB2eqy7i/ekRUtNo8IfMPuRlsSDgn4i5qoQkGINiEbDR4MQdKHcP9DSXIyWGTPRYEMn7he/HQYWBBjyzfo17L8awetPmLjIGa1NSa0C5D+bmmwXwOLxieRPoLJ01XASyCGnCb+JYqXZorhG+exE=,iv:TopMJKo8wLipM6zAw38ezLNaGkXhoRp0bStcBTW3/8w=,tag:xDYFVu2vibLAI+5mRhQgZQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
