---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: graylog
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://charts.kong-z.com/
      chart: graylog
      version: 2.1.8
      sourceRef:
        kind: HelmRepository
        name: kongz
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5

  values:
    graylog:
      env:
      # - TZ: ${CONFIG_TIMEZONE}
      ingress:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: "weather-sunset"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
          #nginx.ingress.kubernetes.io/auth-signin: "https://oauth2.${SECRET_DOMAIN}/oauth2/start?rd=https://$host"
          #nginx.ingress.kubernetes.io/auth-url: "http://oauth2-proxy.networking.svc.cluster.local/oauth2/auth"
        hosts:
          - host: "graylog.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "graylog.${SECRET_DOMAIN}"
            secretName: "graylog"
      persistence:
        enabled: true
        existingClaim: graylog
      podAnnotations:
        backup.velero.io/backup-volumes: storage

    # resources:
    #   requests:
    #     cpu: 20m
    #     memory: 64Mi
    #   limits:
    #     cpu: 100m
    #     memory: 256Mi
